#!/usr/bin/env bash
# finish-app-setup.sh <CODE>
#
# Converts a GitHub App manifest code into the real app, then writes all the
# secrets it returns into packages/infra/.env (alchemy deploy) and
# apps/api/.dev.vars (local dev).
#
# Flow:
#   1. Open scripts/simbox-app-manifest.html in a browser → GitHub creates
#      the app → lands on a URL containing ?code=<CODE>
#   2. Run: ./scripts/finish-app-setup.sh <CODE>
#   3. Download the private key it prints a link for (or grab it from app
#      settings) and paste into packages/infra/.env as GITHUB_APP_PRIVATE_KEY.
set -euo pipefail

CODE="${1:?usage: $0 <code from the redirect URL>}"

resp=$(gh api -X POST "/app-manifests/${CODE}/conversions")

id=$(jq -r .id <<<"$resp")
slug=$(jq -r .slug <<<"$resp")
client_id=$(jq -r .client_id <<<"$resp")
client_secret=$(jq -r .client_secret <<<"$resp")
webhook_secret=$(jq -r .webhook_secret <<<"$resp")
pem=$(jq -r .pem <<<"$resp")

better_secret=$(openssl rand -base64 32)

# Escape for dotenv (PEM has newlines → \n literal)
pem_escaped=$(printf '%s' "$pem" | awk 'NR>1{printf "\\n"}{printf "%s",$0}END{printf "\\n"}' | sed 's/\\n$//')

cat > packages/infra/.env <<ENVEOF
# Generated by scripts/finish-app-setup.sh — $(date -u +%FT%TZ)
GITHUB_APP_ID=${id}
GITHUB_APP_PRIVATE_KEY="${pem_escaped}"
GITHUB_WEBHOOK_SECRET=${webhook_secret}
GITHUB_CLIENT_ID=${client_id}
GITHUB_CLIENT_SECRET=${client_secret}
BETTER_AUTH_SECRET=${better_secret}
APP_URL=
DEMO_MODE=false
ENVEOF

cat > apps/api/.dev.vars <<DEVEOF
# Local dev — generated by scripts/finish-app-setup.sh
# NOTE: the app's OAuth callback points at api.simbox.touchtech.club, so real
# GitHub login won't work locally — use DEMO_MODE or create a dev app.
APP_URL=http://localhost:5173
API_URL=http://localhost:8787
GITHUB_APP_ID=${id}
GITHUB_APP_PRIVATE_KEY="${pem_escaped}"
GITHUB_WEBHOOK_SECRET=${webhook_secret}
GITHUB_CLIENT_ID=${client_id}
GITHUB_CLIENT_SECRET=${client_secret}
BETTER_AUTH_SECRET=${better_secret}
DEMO_MODE=true
DEVEOF

echo "✓ App '${slug}' (id ${id}) created."
echo "✓ Wrote packages/infra/.env and apps/api/.dev.vars"
echo ""
echo "Next:"
echo "  cd packages/infra && bunx alchemy profile edit   # CF credentials (once)"
echo "  bun run deploy                                    # note web URL"
echo "  → set APP_URL in packages/infra/.env, deploy again"
